#!/usr/bin/env python3
"""One-time fail-fast migration for ALLVM usability phase 2."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8")


def replace_once(path: str, old: str, new: str) -> None:
    text = read(path)
    count = text.count(old)
    if count != 1:
        raise SystemExit(
            f"{path}: expected one marker, found {count}: {old[:140]!r}"
        )
    write(path, text.replace(old, new, 1))


def replace_region(path: str, start: str, end: str, replacement: str) -> None:
    text = read(path)
    begin = text.find(start)
    if begin < 0:
        raise SystemExit(f"{path}: missing start marker {start!r}")
    if text.find(start, begin + 1) >= 0:
        raise SystemExit(f"{path}: non-unique start marker {start!r}")
    finish = text.find(end, begin)
    if finish < 0:
        raise SystemExit(f"{path}: missing end marker {end!r}")
    write(path, text[:begin] + replacement + text[finish:])


GENERIC_HELPERS = r'''

def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def directory_logical_stats(path: Path) -> dict[str, int]:
    files = 0
    directories = 0
    logical_bytes = 0
    for root, directory_names, file_names in os.walk(path, followlinks=False):
        directories += len(directory_names)
        root_path = Path(root)
        for file_name in file_names:
            candidate = root_path / file_name
            try:
                logical_bytes += candidate.stat(follow_symlinks=False).st_size
                files += 1
            except OSError:
                continue
    return {
        "files": files,
        "directories": directories,
        "logical_bytes": logical_bytes,
    }


def atomic_copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=str(target.parent), prefix=f".{target.name}.", suffix=".tmp"
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        shutil.copy2(source, temporary)
        os.replace(temporary, target)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
'''


GRADLE_RENDERERS = r'''

def gradle_kotlin_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )


def gradle_groovy_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def render_gradle_kts(options: EffectiveOptions) -> str:
    profile = gradle_kotlin_escape(options.profile.name)
    return f'''// Generated by tools/allvm.py. Regenerate instead of editing by hand.
// Apply from an Android module build.gradle.kts after its plugins block:
// apply(from = rootProject.file(".allvm/allvm.gradle.kts"))

val allvmProfile = "{profile}"
val allvmNdkPath = providers.gradleProperty("allvm.ndkPath")
    .orElse(providers.environmentVariable("ALLVM_NDK_HOME"))
    .orElse(providers.environmentVariable("ANDROID_NDK_HOME"))
    .orElse(providers.environmentVariable("ANDROID_NDK_ROOT"))
    .orNull

fun Any.allvmSetNdkPath(path: String) {{
    val setter = javaClass.methods.firstOrNull {{ method ->
        method.name == "setNdkPath" && method.parameterCount == 1
    }}
    checkNotNull(setter) {{
        "ALLVM: Android Gradle Plugin does not expose ndkPath on ${{javaClass.name}}"
    }}
    setter.invoke(this, path)
}}

listOf(
    "com.android.application",
    "com.android.library",
    "com.android.dynamic-feature",
    "com.android.test",
).forEach {{ pluginId ->
    plugins.withId(pluginId) {{
        extensions.extraProperties.set("allvm.profile", allvmProfile)
        if (!allvmNdkPath.isNullOrBlank()) {{
            extensions.getByName("android").allvmSetNdkPath(allvmNdkPath)
            logger.lifecycle("ALLVM: profile=$allvmProfile, ndkPath=$allvmNdkPath")
        }} else {{
            logger.warn(
                "ALLVM: no custom NDK path; set -Pallvm.ndkPath or ALLVM_NDK_HOME"
            )
        }}
    }}
}}
'''


def render_gradle_groovy(options: EffectiveOptions) -> str:
    profile = gradle_groovy_escape(options.profile.name)
    return f'''// Generated by tools/allvm.py. Regenerate instead of editing by hand.
// Apply from an Android module build.gradle after its plugins block:
// apply from: rootProject.file('.allvm/allvm.gradle')

def allvmProfile = '{profile}'
def allvmNdkPath = providers.gradleProperty('allvm.ndkPath')
    .orElse(providers.environmentVariable('ALLVM_NDK_HOME'))
    .orElse(providers.environmentVariable('ANDROID_NDK_HOME'))
    .orElse(providers.environmentVariable('ANDROID_NDK_ROOT'))
    .orNull

[
    'com.android.application',
    'com.android.library',
    'com.android.dynamic-feature',
    'com.android.test',
].each {{ pluginId ->
    plugins.withId(pluginId) {{
        extensions.extraProperties.set('allvm.profile', allvmProfile)
        if (allvmNdkPath) {{
            extensions.getByName('android').ndkPath = allvmNdkPath
            logger.lifecycle("ALLVM: profile=${{allvmProfile}}, ndkPath=${{allvmNdkPath}}")
        }} else {{
            logger.warn(
                'ALLVM: no custom NDK path; set -Pallvm.ndkPath or ALLVM_NDK_HOME'
            )
        }}
    }}
}}
'''
'''


PROJECT_REGION = r'''PROJECT_GENERATORS = (
    "cmake",
    "ndk-build",
    "gradle-kts",
    "gradle-groovy",
)
GENERATOR_FILENAMES = {
    "cmake": "allvm-options.cmake",
    "ndk-build": "allvm.mk",
    "gradle-kts": "allvm.gradle.kts",
    "gradle-groovy": "allvm.gradle",
}


def load_generation_settings(config_path: Path) -> tuple[Mapping[str, Any], tuple[str, ...]]:
    config = load_json(config_path)
    if config.get("schema") != 1:
        raise CliError(
            f"不支持的项目配置 schema：{config_path} 中为 {config.get('schema')!r}"
        )
    raw_generators = config.get("generate")
    if raw_generators is None:
        generators = ("cmake", "ndk-build")
    else:
        generators = string_list(raw_generators, field="generate", source=config_path)
    if not generators:
        raise CliError(f"{config_path} 的 generate 至少需要一个生成器")
    if len(set(generators)) != len(generators):
        raise CliError(f"{config_path} 的 generate 不能包含重复项")
    unknown = sorted(set(generators) - set(PROJECT_GENERATORS))
    if unknown:
        raise CliError(
            f"{config_path} 包含未知生成器：{', '.join(unknown)}；"
            f"可用值：{', '.join(PROJECT_GENERATORS)}"
        )
    return config, generators


def selected_generators(build_system: str, gradle: str) -> tuple[str, ...]:
    result: list[str] = []
    if build_system in {"cmake", "both"}:
        result.append("cmake")
    if build_system in {"ndk-build", "both"}:
        result.append("ndk-build")
    if gradle in {"kts", "both"}:
        result.append("gradle-kts")
    if gradle in {"groovy", "both"}:
        result.append("gradle-groovy")
    return tuple(result)


def project_readme(profile: Profile, generators: Sequence[str]) -> str:
    sections = [
        "# ALLVM 项目配置",
        "",
        f"当前预设：`{profile.name}`（{profile.title}）",
        "",
        "`allvm.json` 是唯一手工配置源。修改后从项目根目录运行：",
        "",
        "```bash",
        "python3 /path/to/ALLVM/allvm.py sync --directory .",
        "python3 /path/to/ALLVM/allvm.py sync --directory . --check",
        "```",
        "",
        "`allvm.lock.json` 记录预设、配置和生成文件 SHA-256，可由 CI 检查是否过期。",
        "",
    ]
    if "cmake" in generators:
        sections.extend(
            [
                "## CMake",
                "",
                "```cmake",
                "include(${CMAKE_SOURCE_DIR}/.allvm/allvm-options.cmake)",
                "allvm_apply(your_native_target)",
                "```",
                "",
            ]
        )
    if "ndk-build" in generators:
        sections.extend(
            [
                "## ndk-build",
                "",
                "在 `Android.mk` 中，`include $(CLEAR_VARS)` 之后、`BUILD_*` 之前加入：",
                "",
                "```makefile",
                "include $(LOCAL_PATH)/../.allvm/allvm.mk",
                "```",
                "",
            ]
        )
    if "gradle-kts" in generators:
        sections.extend(
            [
                "## Gradle Kotlin DSL",
                "",
                "在 Android 模块 `build.gradle.kts` 的 plugins 块之后加入：",
                "",
                "```kotlin",
                "apply(from = rootProject.file(\".allvm/allvm.gradle.kts\"))",
                "```",
                "",
            ]
        )
    if "gradle-groovy" in generators:
        sections.extend(
            [
                "## Gradle Groovy DSL",
                "",
                "在 Android 模块 `build.gradle` 的 plugins 块之后加入：",
                "",
                "```groovy",
                "apply from: rootProject.file('.allvm/allvm.gradle')",
                "```",
                "",
            ]
        )
    sections.extend(
        [
            "Gradle 片段按顺序读取 `-Pallvm.ndkPath`、`ALLVM_NDK_HOME`、",
            "`ANDROID_NDK_HOME` 和 `ANDROID_NDK_ROOT`，不会写入个人绝对路径。",
            "CMake/ndk-build 的保护参数仍由对应生成文件负责。",
            "",
            "不要把生产 `ALLVM_BUILD_SEED` 写入此目录或提交到 Git。",
            "",
        ]
    )
    return "\n".join(sections)


def generated_project_files(
    options: EffectiveOptions, generators: Sequence[str]
) -> dict[str, str]:
    files: dict[str, str] = {
        "README.md": project_readme(options.profile, generators),
    }
    for generator in generators:
        name = GENERATOR_FILENAMES[generator]
        if generator == "cmake":
            files[name] = render_cmake(options)
        elif generator == "ndk-build":
            files[name] = render_ndk_build(options)
        elif generator == "gradle-kts":
            files[name] = render_gradle_kts(options)
        elif generator == "gradle-groovy":
            files[name] = render_gradle_groovy(options)
    return files


def project_lock_payload(
    config_path: Path,
    options: EffectiveOptions,
    generators: Sequence[str],
    generated: Mapping[str, str],
) -> dict[str, Any]:
    effective = {
        "profile": options.profile.name,
        "compile_options": list(options.compile_options),
        "cxx_options": list(options.cxx_options),
        "link_options": list(options.link_options),
    }
    return {
        "schema": 1,
        "type": "allvm-project-lock",
        "cli_version": VERSION,
        "profile": options.profile.name,
        "profile_sha256": sha256_file(options.profile.source),
        "config_sha256": sha256_file(config_path),
        "effective_options_sha256": sha256_text(
            json.dumps(effective, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        ),
        "generate": list(generators),
        "generated_files": {
            name: sha256_text(content) for name, content in sorted(generated.items())
        },
    }


def synchronize_project(config_path: Path, *, check: bool) -> dict[str, Any]:
    config_path = config_path.expanduser().resolve()
    _, generators = load_generation_settings(config_path)
    options = load_effective_options(profile_name=None, config_path=config_path)
    output = config_path.parent
    generated = generated_project_files(options, generators)
    lock_payload = project_lock_payload(config_path, options, generators, generated)
    lock_text = json.dumps(lock_payload, ensure_ascii=False, indent=2) + "\n"
    expected = dict(generated)
    expected[PROJECT_LOCK] = lock_text

    previous_files: Mapping[str, Any] = {}
    lock_path = output / PROJECT_LOCK
    if lock_path.is_file():
        try:
            previous_lock = load_json(lock_path)
            if previous_lock.get("type") == "allvm-project-lock":
                candidate = previous_lock.get("generated_files", {})
                if isinstance(candidate, dict):
                    previous_files = candidate
        except CliError:
            previous_files = {}

    statuses: list[dict[str, Any]] = []
    obsolete_modified: list[Path] = []
    for name, recorded_hash in sorted(previous_files.items()):
        if name in generated:
            continue
        candidate = output / name
        if not candidate.exists():
            continue
        actual_hash = sha256_file(candidate) if candidate.is_file() else "not-a-file"
        if actual_hash == str(recorded_hash):
            statuses.append({"path": name, "state": "obsolete"})
            if not check:
                candidate.unlink()
        else:
            statuses.append(
                {
                    "path": name,
                    "state": "obsolete-modified",
                    "expected_sha256": str(recorded_hash),
                    "actual_sha256": actual_hash,
                }
            )
            obsolete_modified.append(candidate)

    if obsolete_modified and not check:
        joined = ", ".join(str(path) for path in obsolete_modified)
        raise CliError(f"拒绝删除已修改的过期生成文件：{joined}")

    all_current = not obsolete_modified and not any(
        item["state"] == "obsolete" for item in statuses
    )
    for name, content in expected.items():
        destination = output / name
        if not destination.exists():
            state = "missing"
        elif not destination.is_file():
            state = "not-a-file"
        else:
            try:
                state = (
                    "current"
                    if destination.read_text(encoding="utf-8") == content
                    else "stale"
                )
            except (OSError, UnicodeError):
                state = "stale"

        original_state = state
        if not check and state != "current":
            write_text(destination, content, force=True)
            state = "created" if original_state == "missing" else "updated"
        elif state != "current":
            all_current = False
        statuses.append(
            {
                "path": name,
                "state": state,
                "sha256": sha256_text(content),
            }
        )

    return {
        "schema": 1,
        "mode": "check" if check else "write",
        "ok": all_current if check else True,
        "profile": options.profile.name,
        "config": str(config_path),
        "output": str(output),
        "generate": list(generators),
        "files": statuses,
    }


def print_sync_summary(summary: Mapping[str, Any], *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return
    print(f"ALLVM profile: {summary['profile']}")
    for item in summary["files"]:
        state = str(item["state"])
        label = {
            "current": "OK",
            "created": "CREATE",
            "updated": "UPDATE",
            "missing": "MISS",
            "stale": "STALE",
            "obsolete": "REMOVE" if summary["mode"] == "write" else "OLD",
            "obsolete-modified": "KEEP",
            "not-a-file": "ERROR",
        }.get(state, state.upper())
        print(f"[{label:6}] {item['path']}")


def resolve_project_config(directory: Path, explicit: Optional[Path]) -> Path:
    root = directory.expanduser().resolve()
    if explicit is None:
        return root / ".allvm" / PROJECT_CONFIG
    candidate = explicit.expanduser()
    return candidate.resolve() if candidate.is_absolute() else (root / candidate).resolve()


def command_sync(args: argparse.Namespace) -> int:
    config_path = resolve_project_config(args.directory, args.config)
    summary = synchronize_project(config_path, check=args.check)
    print_sync_summary(summary, as_json=args.json)
    return 0 if summary["ok"] else 1


def command_init(args: argparse.Namespace) -> int:
    directory = args.directory.expanduser().resolve()
    if not directory.exists():
        directory.mkdir(parents=True)
    if not directory.is_dir():
        raise CliError(f"项目路径不是目录：{directory}")

    output = directory / args.output_dir
    if output.exists() and not args.force and any(output.iterdir()):
        raise CliError(f"项目配置目录已存在；使用 --force 刷新：{output}")
    output.mkdir(parents=True, exist_ok=True)

    profile = load_profile(args.profile)
    generators = selected_generators(args.build_system, args.gradle)
    config = {
        "schema": 1,
        "profile": profile.name,
        "generate": list(generators),
        "extra_compile_options": [],
        "remove_compile_options": [],
        "extra_cxx_options": [],
        "remove_cxx_options": [],
        "extra_link_options": [],
        "remove_link_options": [],
    }
    config_path = output / PROJECT_CONFIG
    write_json(config_path, config, force=args.force)
    summary = synchronize_project(config_path, check=False)

    print(f"已初始化 {profile.title}：")
    print(f"  {config_path}")
    for item in summary["files"]:
        print(f"  {output / str(item['path'])}")
    return 0


'''


OVERLAY_HELPERS = r'''

def collect_allvm_tools(
    directory: Path, *, require_compilers: bool = True
) -> dict[str, Path]:
    if not directory.is_dir():
        if require_compilers:
            raise CliError(f"ALLVM 工具目录不存在：{directory}")
        return {}
    tools: dict[str, Path] = {}
    for name in ("clang", "clang++", "ld.lld", "lld"):
        tool = find_tool(directory, name)
        if tool:
            tools[name] = tool
    if require_compilers:
        missing = sorted({"clang", "clang++"} - set(tools))
        if missing:
            raise CliError(f"ALLVM 工具目录缺少：{', '.join(missing)}")
    return tools
'''


OVERLAY_COMMANDS = r'''def overlay_status_payload(overlay: Path, *, include_size: bool) -> dict[str, Any]:
    overlay = overlay.expanduser().resolve()
    manifest = load_overlay_manifest(overlay)
    checks = overlay_verifications(overlay)
    allvm_bin = Path(str(manifest.get("allvm_bin", ""))).expanduser().resolve()
    available_tools = collect_allvm_tools(allvm_bin, require_compilers=False)

    updates: list[dict[str, Any]] = []
    for item in manifest.get("installed_tools", []):
        name = str(item.get("name", ""))
        current_source = available_tools.get(name)
        installed_sha = str(item.get("sha256", ""))
        if current_source is None:
            updates.append(
                {
                    "name": name,
                    "source": "missing",
                    "installed_sha256": installed_sha,
                    "source_sha256": None,
                    "update_available": False,
                }
            )
            continue
        source_sha = sha256_file(current_source)
        updates.append(
            {
                "name": name,
                "source": str(current_source),
                "installed_sha256": installed_sha,
                "source_sha256": source_sha,
                "update_available": source_sha != installed_sha,
            }
        )

    payload: dict[str, Any] = {
        "schema": 1,
        "overlay": str(overlay),
        "source_ndk": manifest.get("source_ndk"),
        "source_revision": manifest.get("source_revision"),
        "allvm_bin": str(allvm_bin),
        "verified": all(check.ok for check in checks),
        "update_available": any(item["update_available"] for item in updates),
        "checks": [
            {
                "name": check.name,
                "status": "PASS" if check.ok else "FAIL",
                "detail": check.detail,
            }
            for check in checks
        ],
        "tools": updates,
    }
    if include_size:
        payload["logical_size"] = directory_logical_stats(overlay)
    return payload


def print_overlay_status(payload: Mapping[str, Any], *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return
    print(f"overlay: {payload['overlay']}")
    print(f"source : {payload['source_ndk']} ({payload['source_revision']})")
    print(f"tools  : {payload['allvm_bin']}")
    print(f"verify : {'PASS' if payload['verified'] else 'FAIL'}")
    print(f"update : {'available' if payload['update_available'] else 'current'}")
    if "logical_size" in payload:
        size = payload["logical_size"]
        print(
            "logical: "
            f"{size['logical_bytes']} bytes, {size['files']} files, "
            f"{size['directories']} directories"
        )
    for item in payload["tools"]:
        state = "UPDATE" if item["update_available"] else "OK"
        if item["source"] == "missing":
            state = "NO-SOURCE"
        print(f"[{state:9}] {item['name']}")


def command_overlay_status(args: argparse.Namespace) -> int:
    payload = overlay_status_payload(args.path, include_size=args.size)
    print_overlay_status(payload, as_json=args.json)
    return 0 if payload["verified"] else 1


def command_overlay_update(args: argparse.Namespace) -> int:
    overlay = args.path.expanduser().resolve()
    manifest = dict(load_overlay_manifest(overlay))
    checks = overlay_verifications(overlay)
    source_checks = [
        check
        for check in checks
        if check.name in {"overlay 与源目录隔离", "overlay source.properties"}
        or check.name.startswith("源 NDK 未变")
    ]
    failed_source = [check for check in source_checks if not check.ok]
    if failed_source:
        details = "; ".join(f"{check.name}: {check.detail}" for check in failed_source)
        raise CliError(f"源 NDK 校验失败，拒绝更新 overlay：{details}")

    if args.allvm_bin:
        allvm_bin = args.allvm_bin.expanduser().resolve()
    else:
        allvm_bin = Path(str(manifest.get("allvm_bin", ""))).expanduser().resolve()
    tools = collect_allvm_tools(allvm_bin)
    relative_prebuilt = Path(str(manifest.get("host_prebuilt", "")))
    if not relative_prebuilt.parts:
        raise CliError("overlay manifest 缺少 host_prebuilt")

    installed_by_name = {
        str(item.get("name", "")): dict(item)
        for item in manifest.get("installed_tools", [])
        if isinstance(item, dict) and item.get("name")
    }
    planned: list[dict[str, Any]] = []
    for name, source_tool in tools.items():
        existing = installed_by_name.get(name)
        if existing and existing.get("path"):
            relative = Path(str(existing["path"]))
        else:
            relative = relative_prebuilt / "bin" / host_tool_name(name)
        target = overlay / relative
        source_sha = sha256_file(source_tool)
        target_sha = sha256_file(target) if target.is_file() else "missing"
        planned.append(
            {
                "name": name,
                "source": str(source_tool),
                "target": str(target),
                "path": str(relative),
                "source_sha256": source_sha,
                "target_sha256": target_sha,
                "changed": source_sha != target_sha,
            }
        )

    changed = [item for item in planned if item["changed"]]
    if not args.dry_run:
        for item in changed:
            atomic_copy_file(Path(item["source"]), Path(item["target"]))

        for item in planned:
            installed_by_name[item["name"]] = {
                "name": item["name"],
                "path": item["path"],
                "source": item["source"],
                "sha256": item["source_sha256"],
            }
        manifest["allvm_bin"] = str(allvm_bin)
        manifest["updated_at"] = dt.datetime.now(dt.timezone.utc).isoformat()
        order = ("clang", "clang++", "ld.lld", "lld")
        manifest["installed_tools"] = [
            installed_by_name[name] for name in order if name in installed_by_name
        ]
        write_json(manifest_path(overlay), manifest, force=True)
        final_checks = overlay_verifications(overlay)
        if not all(check.ok for check in final_checks):
            print_verifications(final_checks, as_json=False)
            raise CliError("overlay 更新后校验失败")

    result = {
        "schema": 1,
        "overlay": str(overlay),
        "allvm_bin": str(allvm_bin),
        "dry_run": bool(args.dry_run),
        "changed": [item["name"] for item in changed],
        "tools": planned,
    }
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        action = "将更新" if args.dry_run else "已更新"
        print(f"{action} {len(changed)} 个工具：{overlay}")
        for item in planned:
            state = "CHANGE" if item["changed"] else "CURRENT"
            print(f"[{state:7}] {item['name']}")
    return 0


'''


PARSER_REPLACEMENT = r'''    sync = commands.add_parser("sync", help="从 allvm.json 刷新全部项目生成文件")
    sync.add_argument("--directory", type=Path, default=Path.cwd())
    sync.add_argument("--config", type=Path, help="默认是 <directory>/.allvm/allvm.json")
    sync.add_argument("--check", action="store_true", help="只检查是否过期，不写文件")
    sync.add_argument("--json", action="store_true")
    sync.set_defaults(handler=command_sync)

    initialize = commands.add_parser("init", help="初始化项目内的 .allvm 配置")
    initialize.add_argument("--directory", type=Path, default=Path.cwd())
    initialize.add_argument("--output-dir", default=".allvm")
    initialize.add_argument("--profile", default="balanced")
    initialize.add_argument(
        "--build-system", choices=("cmake", "ndk-build", "both"), default="both"
    )
    initialize.add_argument(
        "--gradle", choices=("none", "kts", "groovy", "both"), default="none",
        help="同时生成可 apply 的 Gradle NDK 选择片段",
    )
    initialize.add_argument("--force", action="store_true")
    initialize.set_defaults(handler=command_init)
'''


TEST_PROJECT_METHOD = r'''    def test_project_init_sync_gradle_and_config_override(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary) / "project"
            self.run_cli(
                "init",
                "--directory",
                str(project),
                "--profile",
                "balanced",
                "--build-system",
                "both",
                "--gradle",
                "both",
            )
            output = project / ".allvm"
            config_path = output / "allvm.json"
            cmake_path = output / "allvm-options.cmake"
            make_path = output / "allvm.mk"
            kts_path = output / "allvm.gradle.kts"
            groovy_path = output / "allvm.gradle"
            lock_path = output / "allvm.lock.json"
            for path in (
                config_path,
                cmake_path,
                make_path,
                kts_path,
                groovy_path,
                lock_path,
            ):
                self.assertTrue(path.is_file(), path)
            self.assertIn("allvm_apply", cmake_path.read_text(encoding="utf-8"))
            self.assertIn("setNdkPath", kts_path.read_text(encoding="utf-8"))
            self.assertIn("ndkPath", groovy_path.read_text(encoding="utf-8"))

            config = json.loads(config_path.read_text(encoding="utf-8"))
            self.assertEqual(
                config["generate"],
                ["cmake", "ndk-build", "gradle-kts", "gradle-groovy"],
            )
            config["remove_compile_options"] = ["-irobf-fla"]
            config["extra_compile_options"] = ["-DALLVM_PROJECT_TEST=1"]
            config_path.write_text(
                json.dumps(config, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            self.run_cli("sync", "--directory", str(project))
            self.assertNotIn("-irobf-fla", cmake_path.read_text(encoding="utf-8"))
            self.assertIn(
                "-DALLVM_PROJECT_TEST=1", cmake_path.read_text(encoding="utf-8")
            )
            checked = self.run_cli(
                "sync", "--directory", str(project), "--check", "--json"
            )
            self.assertTrue(json.loads(checked.stdout)["ok"])

            cmake_path.write_text("tampered\n", encoding="utf-8")
            stale = self.run_cli(
                "sync", "--directory", str(project), "--check", expected=1
            )
            self.assertIn("STALE", stale.stdout)
            self.run_cli("sync", "--directory", str(project))
            self.assertIn("allvm_apply", cmake_path.read_text(encoding="utf-8"))

            config = json.loads(config_path.read_text(encoding="utf-8"))
            config["generate"].remove("gradle-groovy")
            config_path.write_text(
                json.dumps(config, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            self.run_cli("sync", "--directory", str(project))
            self.assertFalse(groovy_path.exists())
            self.assertTrue(kts_path.exists())

            rendered = self.run_cli(
                "render", "--config", str(config_path), "--format", "lines"
            )
            self.assertNotIn("-irobf-fla\n", rendered.stdout)
            self.assertIn("-DALLVM_PROJECT_TEST=1", rendered.stdout)

            duplicate = self.run_cli(
                "init",
                "--directory",
                str(project),
                "--profile",
                "compat",
                expected=2,
            )
            self.assertIn("--force", duplicate.stderr)

'''


TEST_OVERLAY_METHOD = r'''    def test_overlay_create_status_update_verify_tamper_and_remove(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            ndk, allvm_bin, source_bin = self.make_fake_ndk(root)
            overlay = root / "overlay"
            source_hashes = {
                name: digest(source_bin / tool_name(name))
                for name in ("clang", "clang++", "ld.lld", "lld")
            }

            created = self.run_cli(
                "overlay",
                "create",
                "--ndk",
                str(ndk),
                "--allvm-bin",
                str(allvm_bin),
                "--output",
                str(overlay),
                "--mode",
                "copy",
                "--json",
            )
            manifest = json.loads(created.stdout)
            self.assertEqual(manifest["type"], "allvm-ndk-overlay")
            self.assertEqual(manifest["copy_mode"], "copy")
            self.assertTrue((overlay / ".allvm-overlay.json").is_file())

            overlay_bin = (
                overlay / "toolchains" / "llvm" / "prebuilt" / host_tag() / "bin"
            )
            for name in ("clang", "clang++", "ld.lld", "lld"):
                self.assertEqual(
                    (overlay_bin / tool_name(name)).read_text(encoding="utf-8"),
                    f"allvm-{name}\n",
                )
                self.assertEqual(digest(source_bin / tool_name(name)), source_hashes[name])

            status = self.run_cli(
                "overlay", "status", "--path", str(overlay), "--size", "--json"
            )
            status_payload = json.loads(status.stdout)
            self.assertTrue(status_payload["verified"])
            self.assertFalse(status_payload["update_available"])
            self.assertGreater(status_payload["logical_size"]["logical_bytes"], 0)

            new_clang = allvm_bin / tool_name("clang")
            new_clang.write_text("allvm-clang-v2\n", encoding="utf-8")
            status = self.run_cli(
                "overlay", "status", "--path", str(overlay), "--json"
            )
            self.assertTrue(json.loads(status.stdout)["update_available"])

            dry_run = self.run_cli(
                "overlay",
                "update",
                "--path",
                str(overlay),
                "--dry-run",
                "--json",
            )
            self.assertIn("clang", json.loads(dry_run.stdout)["changed"])
            self.assertEqual(
                (overlay_bin / tool_name("clang")).read_text(encoding="utf-8"),
                "allvm-clang\n",
            )

            updated = self.run_cli(
                "overlay", "update", "--path", str(overlay), "--json"
            )
            self.assertIn("clang", json.loads(updated.stdout)["changed"])
            self.assertEqual(
                (overlay_bin / tool_name("clang")).read_text(encoding="utf-8"),
                "allvm-clang-v2\n",
            )
            self.run_cli("overlay", "verify", "--path", str(overlay))
            for name in ("clang", "clang++", "ld.lld", "lld"):
                self.assertEqual(digest(source_bin / tool_name(name)), source_hashes[name])

            (overlay_bin / tool_name("clang")).write_text(
                "tampered\n", encoding="utf-8"
            )
            failed = self.run_cli(
                "overlay", "verify", "--path", str(overlay), expected=1
            )
            self.assertIn("FAIL", failed.stdout)

            no_confirmation = self.run_cli(
                "overlay", "remove", "--path", str(overlay), expected=2
            )
            self.assertIn("--yes", no_confirmation.stderr)
            self.run_cli("overlay", "remove", "--path", str(overlay), "--yes")
            self.assertFalse(overlay.exists())

'''


def patch_cli() -> None:
    path = "tools/allvm.py"
    replace_once(path, 'VERSION = "0.2.0"', 'VERSION = "0.3.0"')
    replace_once(
        path,
        'PROJECT_CONFIG = "allvm.json"\n',
        'PROJECT_CONFIG = "allvm.json"\nPROJECT_LOCK = "allvm.lock.json"\n',
    )
    replace_once(
        path,
        '''def is_relative_to(path: Path, parent: Path) -> bool:
''',
        GENERIC_HELPERS + '''

def is_relative_to(path: Path, parent: Path) -> bool:
''',
    )
    replace_once(
        path,
        '''def powershell_quote(value: str) -> str:
''',
        GRADLE_RENDERERS + '''

def powershell_quote(value: str) -> str:
''',
    )
    replace_once(
        path,
        '''    if output_format == "ndk-build":
        return render_ndk_build(options)
''',
        '''    if output_format == "ndk-build":
        return render_ndk_build(options)
    if output_format == "gradle-kts":
        return render_gradle_kts(options)
    if output_format == "gradle-groovy":
        return render_gradle_groovy(options)
''',
    )
    replace_once(
        path,
        '''def clone_ndk(source: Path, destination: Path, requested_mode: str) -> str:
''',
        OVERLAY_HELPERS + '''

def clone_ndk(source: Path, destination: Path, requested_mode: str) -> str:
''',
    )
    replace_region(
        path,
        "def project_readme(profile: Profile, build_system: str) -> str:",
        "def command_doctor(args: argparse.Namespace) -> int:",
        PROJECT_REGION,
    )
    replace_once(
        path,
        '''    required = {"clang", "clang++"}
    allvm_tools: dict[str, Path] = {}
    for name in ("clang", "clang++", "ld.lld", "lld"):
        tool = find_tool(allvm_bin, name)
        if tool:
            allvm_tools[name] = tool
    missing = sorted(required - set(allvm_tools))
    if missing:
        raise CliError(f"ALLVM 工具目录缺少：{', '.join(missing)}")
''',
        '''    allvm_tools = collect_allvm_tools(allvm_bin)
''',
    )
    replace_once(
        path,
        '''def command_overlay_verify(args: argparse.Namespace) -> int:
''',
        OVERLAY_COMMANDS + '''
def command_overlay_verify(args: argparse.Namespace) -> int:
''',
    )
    replace_once(
        path,
        'description="ALLVM 统一命令行：诊断、预设、项目初始化和无侵入 NDK overlay。",',
        'description="ALLVM 统一命令行：诊断、预设、项目同步、Gradle 辅助和 NDK overlay。",',
    )
    replace_once(
        path,
        'choices=("json", "cmake", "ndk-build", "shell", "powershell", "rsp", "lines"),',
        'choices=("json", "cmake", "ndk-build", "gradle-kts", "gradle-groovy", "shell", "powershell", "rsp", "lines"),',
    )
    replace_region(
        path,
        '    initialize = commands.add_parser("init", help="初始化项目内的 .allvm 配置")',
        '    doctor = commands.add_parser("doctor", help="诊断 NDK 和构建环境")',
        PARSER_REPLACEMENT,
    )
    replace_once(
        path,
        '''    overlay_verify = overlay_commands.add_parser("verify", help="校验 overlay 和源 NDK 未被修改")
''',
        '''    overlay_status = overlay_commands.add_parser("status", help="汇总校验、更新可用性和可选逻辑大小")
    overlay_status.add_argument("--path", type=Path, required=True)
    overlay_status.add_argument("--size", action="store_true", help="遍历目录并统计逻辑字节数")
    overlay_status.add_argument("--json", action="store_true")
    overlay_status.set_defaults(handler=command_overlay_status)

    overlay_update = overlay_commands.add_parser("update", help="只更新 overlay 中的 ALLVM 主机工具")
    overlay_update.add_argument("--path", type=Path, required=True)
    overlay_update.add_argument("--allvm-bin", type=Path, help="省略时使用 manifest 中的目录")
    overlay_update.add_argument("--dry-run", action="store_true")
    overlay_update.add_argument("--json", action="store_true")
    overlay_update.set_defaults(handler=command_overlay_update)

    overlay_verify = overlay_commands.add_parser("verify", help="校验 overlay 和源 NDK 未被修改")
''',
    )


def patch_tests() -> None:
    path = "tools/test-allvm-cli.py"
    replace_once(
        path,
        '''        shell = self.run_cli("render", "--profile", "strong", "--format", "shell")
        self.assertIn("-irobf-vmp", shell.stdout)
''',
        '''        shell = self.run_cli("render", "--profile", "strong", "--format", "shell")
        self.assertIn("-irobf-vmp", shell.stdout)

        gradle_kts = self.run_cli(
            "render", "--profile", "balanced", "--format", "gradle-kts"
        )
        self.assertIn("setNdkPath", gradle_kts.stdout)
        self.assertIn("ALLVM_NDK_HOME", gradle_kts.stdout)
        self.assertIn('allvmProfile = "balanced"', gradle_kts.stdout)

        gradle_groovy = self.run_cli(
            "render", "--profile", "compat", "--format", "gradle-groovy"
        )
        self.assertIn("ndkPath", gradle_groovy.stdout)
        self.assertIn("allvmProfile = 'compat'", gradle_groovy.stdout)
''',
    )
    replace_region(
        path,
        "    def test_project_init_and_config_override(self) -> None:",
        "    def make_fake_ndk(self, root: Path) -> tuple[Path, Path, Path]:",
        TEST_PROJECT_METHOD,
    )
    replace_region(
        path,
        "    def test_overlay_create_verify_tamper_and_remove(self) -> None:",
        "    def test_overlay_force_refuses_unmarked_directory(self) -> None:",
        TEST_OVERLAY_METHOD,
    )


def patch_docs() -> None:
    path = "README.md"
    replace_once(
        path,
        "- **当前易用性分支**：`usability/p1-cli-presets-overlay`",
        "- **当前易用性分支**：`usability/p2-sync-gradle-overlay-status`",
    )
    replace_once(
        path,
        '''├── render       生成 CMake、ndk-build、shell、JSON 或响应文件参数
├── init         在项目内生成 .allvm 配置与接入片段
└── overlay      创建、校验和删除不修改源 NDK 的独立副本
''',
        '''├── render       生成 CMake、ndk-build、Gradle、shell、JSON 或响应文件参数
├── init         在项目内生成 .allvm 配置与接入片段
├── sync         从 allvm.json 原子刷新全部生成文件并维护 lock
└── overlay      创建、状态、增量更新、校验和删除独立 NDK
''',
    )
    replace_once(
        path,
        '''  --profile balanced \\
  --build-system both
''',
        '''  --profile balanced \\
  --build-system both \\
  --gradle both
''',
    )
    replace_once(
        path,
        '''# 3. 验证副本工具哈希和源 NDK 未发生变化
python3 /path/to/ALLVM/allvm.py overlay verify \\
  --path ~/.allvm/ndk/r29-allvm
''',
        '''# 3. 查看校验、更新可用性和逻辑大小
python3 /path/to/ALLVM/allvm.py overlay status \\
  --path ~/.allvm/ndk/r29-allvm \\
  --size

# 4. 修改 allvm.json 后统一刷新，并在 CI 检查生成文件未过期
python3 /path/to/ALLVM/allvm.py sync --directory .
python3 /path/to/ALLVM/allvm.py sync --directory . --check
''',
    )
    replace_once(
        path,
        "git switch usability/p1-cli-presets-overlay",
        "git switch usability/p2-sync-gradle-overlay-status",
    )
    replace_once(
        path,
        '''python3 allvm.py render --profile balanced --format ndk-build
python3 allvm.py render --profile strong --format json
''',
        '''python3 allvm.py render --profile balanced --format ndk-build
python3 allvm.py render --profile balanced --format gradle-kts
python3 allvm.py render --profile strong --format json
''',
    )
    replace_once(
        path,
        '''├── allvm.mk
└── README.md
''',
        '''├── allvm.mk
├── allvm.gradle.kts / allvm.gradle（按 --gradle 选择）
├── allvm.lock.json
└── README.md
''',
    )
    replace_once(
        path,
        "`init` 会生成：",
        "`init` 会生成；之后只编辑 `allvm.json`，再运行 `allvm sync`：",
    )

    usage = "docs/ALLVM_USAGE_CN.md"
    replace_once(
        usage,
        '''├── render            输出 shell/CMake/ndk-build/JSON/响应文件参数
├── init              在项目中生成 .allvm 配置和接入片段
└── overlay           创建、校验和删除独立 NDK 副本
''',
        '''├── render            输出 shell/CMake/ndk-build/Gradle/JSON/响应文件参数
├── init              在项目中生成 .allvm 配置和接入片段
├── sync              原子刷新生成文件、维护 lock、CI 检查过期
└── overlay           创建、状态、增量更新、校验和删除独立 NDK
''',
    )
    replace_once(
        usage,
        '''查看 manifest：

```bash
python3 allvm.py overlay info --path ~/.allvm/ndk/r29-allvm
```
''',
        '''查看综合状态和可选逻辑大小：

```bash
python3 allvm.py overlay status \\
  --path ~/.allvm/ndk/r29-allvm \\
  --size
```

重新编译 ALLVM 主机工具后，无需复制整个 NDK，只更新副本中的工具：

```bash
python3 allvm.py overlay update \\
  --path ~/.allvm/ndk/r29-allvm \\
  --allvm-bin /path/to/new/allvm/bin \\
  --dry-run
python3 allvm.py overlay update \\
  --path ~/.allvm/ndk/r29-allvm \\
  --allvm-bin /path/to/new/allvm/bin
```

`update` 会先验证源 NDK 哈希；源工具发生变化时拒绝更新。省略 `--allvm-bin` 时使用 manifest 中记录的目录。查看原始 manifest：

```bash
python3 allvm.py overlay info --path ~/.allvm/ndk/r29-allvm
```
''',
    )
    replace_once(
        usage,
        '''  --profile balanced \\
  --build-system both
''',
        '''  --profile balanced \\
  --build-system both \\
  --gradle both
''',
    )
    replace_once(
        usage,
        '''├── allvm.mk
└── README.md
''',
        '''├── allvm.mk
├── allvm.gradle.kts
├── allvm.gradle
├── allvm.lock.json
└── README.md
''',
    )
    replace_once(
        usage,
        '''`--force` 只刷新 `.allvm` 中的生成文件，不会修改项目其他文件。

## 3. CMake 接入
''',
        '''`--force` 只初始化 `.allvm`，不会修改项目其他文件。日常修改只编辑 `allvm.json`，然后运行：

```bash
python3 allvm.py sync --directory .
python3 allvm.py sync --directory . --check
```

`sync` 原子刷新选择的生成文件和 `allvm.lock.json`。`--check` 不写文件，缺失、过期或存在可安全删除的旧生成文件时返回 1，适合 CI。切换 `generate` 后，未修改的旧生成文件会自动删除；用户改过的旧生成文件会保留并报错。

## 3. CMake 接入
''',
    )
    replace_region(
        usage,
        "## 5. Gradle/Android Studio 接入",
        "## 6. 参数渲染格式",
        '''## 5. Gradle/Android Studio 接入

CLI 不直接改写 `build.gradle` 或 `build.gradle.kts`。初始化时使用：

```bash
python3 allvm.py init \\
  --directory . \\
  --profile balanced \\
  --build-system cmake \\
  --gradle both
```

Kotlin DSL 模块在 plugins 块之后加入：

```kotlin
apply(from = rootProject.file(".allvm/allvm.gradle.kts"))
```

Groovy DSL：

```groovy
apply from: rootProject.file('.allvm/allvm.gradle')
```

生成片段按顺序读取：

```text
-Pallvm.ndkPath
ALLVM_NDK_HOME
ANDROID_NDK_HOME
ANDROID_NDK_ROOT
```

找到路径后设置 Android Gradle Plugin 的 `ndkPath`。个人绝对路径不会写进仓库；保护参数仍由 `allvm-options.cmake` 或 `allvm.mk` 管理。Gradle 原生构建继续使用模块已有的 `externalNativeBuild.cmake` 或 `externalNativeBuild.ndkBuild` 配置。

也可单独渲染：

```bash
python3 allvm.py render --profile balanced --format gradle-kts
python3 allvm.py render --profile balanced --format gradle-groovy
```

## 6. 参数渲染格式
''',
    )
    replace_once(
        usage,
        '''| `ndk-build` | 可 include 的 Android.mk 片段 |
| `shell` | POSIX shell 参数 |
''',
        '''| `ndk-build` | 可 include 的 Android.mk 片段 |
| `gradle-kts` | 可 apply 的 Kotlin DSL NDK 选择片段 |
| `gradle-groovy` | 可 apply 的 Groovy DSL NDK 选择片段 |
| `shell` | POSIX shell 参数 |
''',
    )
    replace_once(
        usage,
        '''  "profile": "balanced",
  "extra_compile_options": [],
''',
        '''  "profile": "balanced",
  "generate": ["cmake", "ndk-build", "gradle-kts"],
  "extra_compile_options": [],
''',
    )
    replace_once(
        usage,
        '''python3 allvm.py profile list
python3 allvm.py render --profile balanced --format json > allvm-flags.json
python3 allvm.py overlay verify --path "$ANDROID_NDK_HOME"
''',
        '''python3 allvm.py profile list
python3 allvm.py sync --directory . --check
python3 allvm.py render --profile balanced --format json > allvm-flags.json
python3 allvm.py overlay status --path "$ANDROID_NDK_HOME" --json
python3 allvm.py overlay verify --path "$ANDROID_NDK_HOME"
''',
    )


def main() -> int:
    patch_cli()
    patch_tests()
    patch_docs()
    print("usability phase 2 migration applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
